### ISSUE TITLE
执行的时报错

### ISSUE THREAD

**Issue by Minelu** [jimlee2002/WoZaiXiaoYuanPuncher-Actions#12]
执行时报错，修改Cache name后执行一次正常，下一次自动执行又报错
Run python wzxy-dailyreport.py
找到cache文件，尝试使用jwsession打卡...
获取打卡列表中...
jwsession 无效，将尝试使用账号信息重新登录
使用账号信息登录成功
找到cache文件，正在更新cache中的jwsession...
Traceback (most recent call last):
  File "/home/runner/work/WoZaiXiaoYuanPuncher-Actions/WoZaiXiaoYuanPuncher-Actions/wzxy-dailyreport.py", line 235, in <module>
    wzxy.PunchIn()
  File "/home/runner/work/WoZaiXiaoYuanPuncher-Actions/WoZaiXiaoYuanPuncher-Actions/wzxy-dailyreport.py", line 91, in PunchIn
    loginStatus = self.login()
  File "/home/runner/work/WoZaiXiaoYuanPuncher-Actions/WoZaiXiaoYuanPuncher-Actions/wzxy-dailyreport.py", line 44, in login
    self.setJwsession(jwsession)
  File "/home/runner/work/WoZaiXiaoYuanPuncher-Actions/WoZaiXiaoYuanPuncher-Actions/wzxy-dailyreport.py", line 67, in setJwsession
    item['jwsession'] = jwsession                 
TypeError: 'str' object does not support item assignment
Error: Process completed with exit code 1.

**Comment by jimlee2002** [comment]
已在 2021.09.28 后的版本解决该问题，请手动 fetch 一下最新脚本。
